export const Fonts = {
  poppins: {
    regular: 'Poppins-Regular',
    black: 'Poppins-Black',
    blackItalic: 'Poppins-BlackItalic',
    bold: 'Poppins-Bold',
    boldItalic: 'Poppins-BoldItalic',
    extraBold: 'Poppins-ExtraBold',
    extraBoldItalic: 'Poppins-ExtraBoldItalic',
    extraLight: 'Poppins-ExtraLight',
    extraLightItalic: 'Poppins-ExtraLightItalic',
    italic: 'Poppins-Italic',
    light: 'Poppins-Light',
    lightItalic: 'Poppins-LightItalic',
    medium: 'Poppins-Medium',
    mediumItalic: 'Poppins-MediumItalic',
    semiBold: 'Poppins-SemiBold',
    semiBoldItalic: 'Poppins-SemiBoldItalic',
    thin: 'Poppins-Thin',
    thinItalic: 'Poppins-ThinItalic',
  },
  dancingScript: {
    bold: 'DancingScript-Bold',
    medium: 'DancingScript-Medium',
    regular: 'DancingScript-Regular',
    semiBold: 'DancingScript-SemiBold',
  },
  hindi: {
    hindi: 'hindi',
    hindi1: 'hindi1',
    hindi3: 'hindi3',
  },
  lobster: {
    regular: 'Lobster-Regular',
  },
  roboto: {
    black: 'Roboto-Black',
    blackItalic: 'Roboto-BlackItalic',
    bold: 'Roboto-Bold',
    boldItalic: 'Roboto-BoldItalic',
    italic: 'Roboto-Italic',
    light: 'Roboto-Light',
    lightItalic: 'Roboto-LightItalic',
    medium: 'Roboto-Medium',
    mediumItalic: 'Roboto-MediumItalic',
    regular: 'Roboto-Regular',
    thin: 'Roboto-Thin',
    thinItalic: 'Roboto-ThinItalic',
  },
};
